from .schema import (
    EMBEDDING_DIMENSION,
    embedding_column_type,
    face_labels,
    faces,
    ingest_runs,
    ingest_run_files,
    ingest_queue,
    metadata,
    people,
    photo_files,
    photo_tags,
    photos,
    storage_source_aliases,
    storage_sources,
    watched_folders,
    configure_embedding_column,
)

__all__ = [
    "EMBEDDING_DIMENSION",
    "configure_embedding_column",
    "embedding_column_type",
    "face_labels",
    "faces",
    "ingest_runs",
    "ingest_run_files",
    "ingest_queue",
    "metadata",
    "people",
    "photo_files",
    "photo_tags",
    "photos",
    "storage_source_aliases",
    "storage_sources",
    "watched_folders",
]
